### ISSUE TITLE
Bloque Alianzas

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#12]
Me gusta cómo está ese bloque en Móvil pero no en Escritorio. ¿Se podríe poner en éste último como una galería y no con un scroll horizontal?

**Comment by dacmail** [comment]
Lo hablamos en la reu. Que lo querrías como un grid de fotos? No te mola en serio el scroll nativo ahí? como lo ves tu? Yo l veo bastante fino :D

![image](https://user-images.githubusercontent.com/11754/96560765-006b0800-12bf-11eb-8fe7-2cf4e411843b.png)

**Comment by pr3ssh** [comment]
Me mola mucho en móvil pero en escritorio tengo dudas. Lo he comentado también internamente. Lo hablamos en la reunión.
