### ISSUE TITLE
Creo que necesitamos más espacio entre secciones tanto en la versión móvil como en escritorio

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#15]
Estoy usando H1 como titulo de pagina y luego H2 como "secciones" ([ver aquí](https://politicalwatch-dev.netlify.app/que-hacemos/democracia/)) y normalmente H3 para lo que debería ser un H2. Espero explicarme bien. Si no, lo hablamos.

**Comment by dacmail** [comment]
Lo vemos esta tarde, he añadido separadores de sección al bloque de contenido de markdwn que no lo tenía, no se si esto soluciona lo que comentas.

No obstante dentro del markdown nunca se debe usar un h1, ya que este es incluido como títul de página de forma automática.
