### ISSUE TITLE
/en/investigaciones not found

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#18]
Cómo podemos resolver esto?

**Comment by dacmail** [comment]
Es que no está creado el markdown no? Las investigaciones no las vais a subir en inglés?

**Comment by pr3ssh** [comment]
No lo sé. Lo pregunto.

**Comment by pr3ssh** [comment]
Ya se lo que vamos a hacer. Cierro por aquí.
