### ISSUE TITLE
Los artículos del blog deben de tener un campo date y que ordenen por él y no por la fecha de guardado

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#26]

**Comment by dacmail** [comment]
Tienen el campo createdAt, esto ya lo cambiamos cuando hicimos una llamada, ese campo no es necesario meterlo en el frontmatter ya que lo pilla de la fecha de creación del archivo, aunque creo que tu mismo puedes sustituirlo en el frontmatter

**Comment by pr3ssh** [comment]
@dacmail Gracias. Creo que sí, que vamos a tener que sustituirlo en el _frontmatter_ dado que ayer migramos todos los articulos del blog anterior por lo que se crearon con fecha de ayer.

@dlled ¿Te encargas y actualizas la [PR](https://github.com/politicalwatch/politicalwatch.es/pull/25)?

**Comment by dacmail** [comment]
Guay, he hecho una prueba y podéis hacerlo manteniendo el formato:

```
createdAt: 2020-10-27
```

o 

```
createdAt: 2020-10-26T12:26:48.696Z
```

**Comment by pr3ssh** [comment]
@dlled Con fecha (sin hora) nos vale
