### ISSUE TITLE
Hacer que el contenido de la Hero section sea rotativo

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#3]
Extraído de la documentación:

_En el banner inicial además de la imagen pondría alguno de los slogans que pensamos en su momento: 
Datos para la innovación política
Datos para el cambio social
Tenemos dos slogans, Ver cómo solucionarlo en la web con el equipo de diseño: se propone dejar el “Datos para” fijo y que los otros dos elementos aparezcan y desaparezcan (fade out y fade in u otra opción como que aparezcan de abajo y desaparezca hacia arriba o como sea)._

**Comment by dacmail** [comment]
Ya está, he metido una animación de aparición desde arriba.Tu me dices si la ves ok y cierras tarea en ese caso.
