### ISSUE TITLE
La paginación del Blog no funciona correctamente

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#30]

**Comment by dacmail** [comment]
@pr3ssh Qué le pasa exactamente? No veo nada raro..

**Comment by pr3ssh** [comment]
Creo que el filtrado o el orden de la página/1 (al menos) no es el correcto.

**Comment by dacmail** [comment]
Vale!! Yo es que estaba mirando a ver si daba algún error, creo que era por el orden que cambiamos en el index del blog pero no en la paginación
