### ISSUE TITLE
Poder cambiar el title y el subtitle del componente PROJECTS o por parámetro o por idioma

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#32]
El title siempre será el mismo: Proyectos

pero el subtitle será diferente para la página Democracia y Coherencia.

Te paso los textos que llevaría:

* Democracia: Plataformas ciudadanas, herramientas de monitoreo parlamentario y campañas de incidencia pública. Todo ello basado en tecnologías cívicas.
* Coherencia: Consultorías, asesorías e investigaciones centradas en el análisis de los procesos de construcción y diseño de políticas públicas con un enfoque de género, derechos humanos y desarrollo sostenible.

**Comment by dacmail** [comment]
Listo, ahora al componente `<projects>` le puedes pasar las props `title` y `subtitle`
