### ISSUE TITLE
Poder ordenar las alianzas

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#5]
Lo mismo que los miermbros del equipo.

**Comment by dacmail** [comment]
@pr3ssh en principio las alianzas sí las he dejado como un array dentro del frontmatter, por el hecho de que no le veo entidad suficiente y así permite poder usar ese bloque en determinadas páginas con logos distintos, por lo tanto el orden se puede manipular facilmente desde el propio MD.

Dime si prefieres que cada "aliado" tenga un MD y lo preparo, pero en ese caso yo no lo veía tan claro como con Equipo

**Comment by pr3ssh** [comment]
Lo dejamos tal y como está.
