### ISSUE TITLE
En la vista de INvestigaciones > Tag, contextualizar más la página

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#7]
Poner que es una categoría o tag de investigación

INVESTIGACIONES de TAG

o algo asi...

**Comment by dacmail** [comment]
Lo puse al principio pero no cabe por ejemplo con "Investigaciones: Congreso de los diputados", se lo comentamos a rubén, a ver si como subtítulo o algo...
