### ISSUE TITLE
Meter en la página de Democracia y Coherencia las 3 últimas entradas del blog de esa categoría

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#8]
Sé que aun estabas con el blog pero dejo esto por aqui para que no se nos olvide.

**Comment by dacmail** [comment]
@pr3ssh los posts no tienen categorías (no se muestran en ningún sitio). Cómo hacemos? Le metemos un campo nuevo `type: coherence | democracy` como en los proyectos o lo dejamos eso en los tags de los artículos, de forma que se muestren las noticias *etiquetadas* con democracia o coherencia?

**Comment by pr3ssh** [comment]
Mete un campo `line-of-work` porque algunos artículos no serán ni de una categoría ni de otra y quiero mezclarlos con los tags.
