### ISSUE TITLE
Cómo se hace para que en Democracia vayan los proyectos de esa línea (igual con Coherencia)?

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/politicalwatch.es#9]

**Comment by dacmail** [comment]
No se puede actualmente, qué hacemos, le meto a los proyectos un campo `type: coherence | democracy` y que se muestren según se especifique?

**Comment by pr3ssh** [comment]
Mete mejor un campo `line-of-work`

**Comment by dacmail** [comment]
Perfe!. por casualidad en las investigaciones quieres hacer lo mismo?
